#! /bin/sh
### BEGIN INIT INFO
# Provides:          epgrecd
# Required-Start:    $local_fs mythtv-backend
# Required-Stop:     $local_fs mythtv-backend
# Default-Start:     90 99
# Default-Stop:      S
# Short-Description: Start/Stop the MythTV external record daemon.
### END INIT INFO

# ※↑は適当です。

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/lib/extrec/epgrecd.pl
NAME="epgrecd"
DESC="EPGrecd"

test -x $DAEMON || exit 0

set -e

USER=tomoaki
RUNDIR=/var/run/mythtv
LOCKFILE=/var/lock/friiodetect
ARGS="--pidfile $RUNDIR/$NAME.pid"
NICE=0

mkdir -p $RUNDIR
chown -R $USER $RUNDIR

case "$1" in
  start)
	if test -e $RUNDIR/$NAME.pid ; then
		echo "$NAME already running, use restart instead."
	else
		echo -n "Starting $DESC: $NAME"
		touch $LOCKFILE
		chmod 0666 $LOCKFILE
		start-stop-daemon --start --pidfile $RUNDIR/$NAME.pid \
			--chuid $USER --nicelevel $NICE --exec $DAEMON -- $ARGS
		echo "."
	fi
	;;
  stop)
	echo -n "Stopping $DESC: $NAME "
	start-stop-daemon --stop --oknodo --pidfile $RUNDIR/$NAME.pid \
		--chuid $USER
	test -e $RUNDIR/$NAME.pid && rm $RUNDIR/$NAME.pid
	echo "."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: $NAME"
	start-stop-daemon --stop --oknodo --pidfile $RUNDIR/$NAME.pid \
                --chuid $USER
	echo "."
	sleep 3
	start-stop-daemon --start --pidfile $RUNDIR/$NAME.pid \
                --chuid $USER --nicelevel $NICE --exec $DAEMON -- $ARGS
	echo "."
	;;
  reload)
  	echo -n "Reloading schedule"
	kill -HUP `cat $RUNDIR/$NAME.pid`
	echo "."
  	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
